nelmio_api_doc:
    documentation:
        info:
            title: Wish list
            version: 1.0.0

        paths:
            /oauth/v2/token:
                post:
                    tags:
                        - oAuth
                    description: Authorises client via client_id and client_secret and returns token
                    security: []
                    consumes:
                        - application/x-www-form-urlencoded
                    produces:
                        - application/json
                    parameters:
                        - name: client_id
                          description: Client public token
                          in: formData
                          type: string
                          required: true
                        - name: client_secret
                          description: Client secret token
                          in: formData
                          type: string
                          required: true
                        - name: grant_type
                          in: formData
                          required: true
                          type: string
                          default: client_credentials
                          description: Allowed types => client_credentials, password, refresh_token
                        - name: username
                          in: formData
                          required: false
                          type: string
                          description: Username
                        - name: password
                          in: formData
                          required: false
                          type: string
                          description: Password
                        - name: refresh_token
                          in: formData
                          required: false
                          type: string
                          description: Refresh token
                    responses:
                        '200':
                            description: Verified successful
                            schema:
                                type: object
                                properties:
                                  access_token:
                                    type: string
                                    example: access_token
                                  expires_in:
                                    type: string
                                    example: expires_in
                                  token_type:
                                    type: string
                                    example: bearer
                                  scope:
                                    type: string
                                    example: scope

                        '400':
                            description: login error
                            schema:
                                type: object
                                properties:
                                    error:
                                        type: string
                                        example: invalid_client
                                    error_description:
                                        type: string
                                        example: The client credentials are invalid

        parameters:
            authorization:
                name: 'Authorization'
                description: 'Bearer authorization'
                default: 'Bearer NzAyOGNmMjUJRzk0MTQyYWRjNmE4ODA1NGQ5YTkyOWYwNjY4MThkNDk0N2VlMDg0YmZjMjVhNDgwYjc5NDNjMQ'
                required: true
                in: 'header'
                type: 'string'
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
